import type {
  Industry,
  IndustrySource,
  IndustryRule,
  SourceField,
} from "./industries";
const field = (
  id: string,
  label: string,
  type: SourceField["type"],
  value: SourceField["value"],
  unit?: string,
): SourceField => ({ id, label, type, value, ...(unit ? { unit } : {}) });
const source = (
  id: string,
  name: string,
  short: string,
  role: string,
  fields: SourceField[],
): IndustrySource => ({
  id,
  name,
  short,
  role,
  system: `${role} records`,
  schema: `demo:supplier:${id}:v1`,
  fields,
});
const rule = (
  source: string,
  field: string,
  label: string,
  operator: IndustryRule["operator"],
  value: IndustryRule["value"],
): IndustryRule => ({ source, field, label, operator, value });
export const supplierIndustry: Industry = {
  id: "supplier",
  name: "Supplier assurance",
  headline: "One supplier. Seven authorities. Twenty conditions.",
  description:
    "Qualify a supplier for Project 817 using insurance, audit, certification, financial, cyber, screening and capacity evidence. Each institution remains responsible for its own signed statements.",
  color: "green",
  holder: "Atlas Industrial Controls",
  subject: "supplier:atlas-industrial-controls",
  verifier: "Northstar Procurement",
  purpose: "Project 817 supplier qualification",
  sources: [
    source("insurance", "Harbor Mutual", "HM", "Commercial insurer", [
      field("aggregate", "Aggregate coverage", "number", 5000000, "USD"),
      field("occurrence", "Per-occurrence coverage", "number", 2000000, "USD"),
      field("additional", "Additional insured supported", "boolean", true),
      field("waiver", "Subrogation waiver supported", "boolean", true),
      field("validThrough", "Coverage valid through", "date", "2027-12-31"),
    ]),
    source("audit", "Cedar Assurance", "CA", "Independent auditor", [
      field("reportType", "Report type", "text", "type-ii"),
      field("periodMonths", "Examination period", "number", 12, "months"),
      field("security", "Security criterion in scope", "boolean", true),
      field("exceptions", "Material exceptions", "number", 0),
    ]),
    source(
      "quality",
      "Meridian Certification",
      "MC",
      "Quality certification body",
      [
        field("current", "Certification current", "boolean", true),
        field(
          "scope",
          "Certified activity",
          "text",
          "manufacturing-industrial-controls",
        ),
        field(
          "validThrough",
          "Certificate valid through",
          "date",
          "2028-12-31",
        ),
      ],
    ),
    source(
      "finance",
      "Crescent Commercial Bank",
      "CB",
      "Financial capacity attestor",
      [
        field("liquidity", "Confirmed liquid funds", "number", 900000, "USD"),
        field(
          "validThrough",
          "Confirmation valid through",
          "date",
          "2027-12-31",
        ),
      ],
    ),
    source("cyber", "Beacon Cyber Underwriters", "BC", "Cyber insurer", [
      field("coverage", "Cyber coverage limit", "number", 3000000, "USD"),
      field("validThrough", "Cyber policy valid through", "date", "2027-12-31"),
    ]),
    source(
      "screening",
      "ClearPath Trade Review",
      "CT",
      "Trade screening provider",
      [
        field(
          "eligible",
          "Eligible under Project 817 screening profile",
          "boolean",
          true,
        ),
        field(
          "validThrough",
          "Screening acceptance valid through",
          "date",
          "2027-12-31",
        ),
      ],
    ),
    source(
      "capacity",
      "Foundry Operations Assessment",
      "FO",
      "Production capacity assessor",
      [
        field(
          "units",
          "Available industrial-control units per month",
          "number",
          1500,
        ),
        field(
          "validThrough",
          "Capacity assessment valid through",
          "date",
          "2027-12-31",
        ),
      ],
    ),
  ],
  rules: [
    rule("insurance", "aggregate", "CGL aggregate ≥ $2M", "gte", 2000000),
    rule("insurance", "occurrence", "Per occurrence ≥ $1M", "gte", 1000000),
    rule("insurance", "additional", "Additional-insured assertion", "eq", true),
    rule("insurance", "waiver", "Subrogation waiver assertion", "eq", true),
    rule(
      "insurance",
      "validThrough",
      "Insurance covers project end",
      "gte",
      "2027-06-30",
    ),
    rule("audit", "reportType", "SOC 2 Type II assertion", "eq", "type-ii"),
    rule("audit", "periodMonths", "Examination period ≥ 6 months", "gte", 6),
    rule("audit", "security", "Security criterion in scope", "eq", true),
    rule("audit", "exceptions", "No material exceptions", "lte", 0),
    rule("quality", "current", "ISO 9001 assertion current", "eq", true),
    rule(
      "quality",
      "scope",
      "Contracted manufacturing activity in scope",
      "eq",
      "manufacturing-industrial-controls",
    ),
    rule(
      "quality",
      "validThrough",
      "Quality certificate covers project end",
      "gte",
      "2027-06-30",
    ),
    rule("finance", "liquidity", "Liquid funds ≥ $500k", "gte", 500000),
    rule(
      "finance",
      "validThrough",
      "Financial confirmation covers engagement",
      "gte",
      "2027-06-30",
    ),
    rule("cyber", "coverage", "Cyber coverage ≥ $1M", "gte", 1000000),
    rule(
      "cyber",
      "validThrough",
      "Cyber policy covers project end",
      "gte",
      "2027-06-30",
    ),
    rule(
      "screening",
      "eligible",
      "Eligible under the named screening profile",
      "eq",
      true,
    ),
    rule(
      "screening",
      "validThrough",
      "Screening acceptance covers engagement",
      "gte",
      "2027-06-30",
    ),
    rule(
      "capacity",
      "units",
      "Available capacity ≥ 1000 units/month",
      "gte",
      1000,
    ),
    rule(
      "capacity",
      "validThrough",
      "Capacity assessment covers engagement",
      "gte",
      "2027-06-30",
    ),
  ],
  failure: {
    source: "finance",
    field: "liquidity",
    value: 100000,
    label: "Insufficient financial capacity",
  },
};
